package sbnz.integracija;

import sbnz.integracija.example.facts.Subscriber;
import sbnz.integracija.example.facts.Course;


global String area;
global String idAuthor;


rule "Special discout when subscriber has two and more completed courses in same area!"
    agenda-group "special-discout"
    lock-on-active true
    when
        $s: Subscriber($courses : completedCourses)
        Number (intValue >= 2) from accumulate(
            Course( courseAres == area, $c: this ) from $courses,
            count($c)
        )
    then
    modify($s){incrementDiscount(10)}
end

rule "Special discout when subscriber has two and more completed courses by the same author!"
    agenda-group "special-discout"
    lock-on-active true
    when
        $s: Subscriber($courses : completedCourses)
                Number (intValue >= 2) from accumulate(
                    Course($t: teacher, $t.userId == idAuthor ) from $courses,
                    count($t)
                )
        then
            modify($s){incrementDiscount(10)}
end